### ISSUE TITLE
custom headers cannot be used

### ISSUE THREAD

**Issue by gorgonaut04** [ctheiss/simple-requests#6]
At least not that I can tell. There is a site I am scraping that won't provide the data I need unless I provide the request with custom headers. Is there a way to do this, similarly to Requests?

**Comment by ctheiss** [comment]
There sure is!  By default, if you pass `one`, `swarm`, or `each` a string, it will build a simple GET `Request` and then execute it.  But, you can build your own `Request` and pass that in, instead of a string.  You would need to do this if you'd like to POST, or attach custom headers to a single request.

Alternatively, if you're passing in the same custom headers for every request, you can add them to the session:

    requests = Requests()
    requests.session.headers['custom-header'] = 'Moop'
